# Generated by Django 5.0.4 on 2024-05-29 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('store', '0002_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
